In [2]:
import plotly.graph_objs as go
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
fig = go.Figure(data=go.Scatter(x=x**3))
fig.show()

In [6]:
# Outra forma de escrever: 
data = go.Scatter(x=x**3)
fig = go.Figure(data)
fig.show()

In [12]:
# Gerando os dados para os exemplos
N = 50 
x = np.linspace(0,1,N)
random_y = np.random.normal(30, 2.5,N)

In [13]:
# Plotando a figura

linha = [go.Scatter(
    x = x,
    y = random_y,
    mode = 'lines',
    name = 'Linha 1',
    line = dict(color='black')
)]

layout = go.Layout(
    title = 'Minha figura',
    xaxis = dict(title = 'Eixo X'),
    yaxis= dict(title= 'Eixo Y')
)

fig = go.Figure(data= linha, layout=layout)

fig.show()

In [16]:
# Gerando novas variaveis para mais exemplos
random_y1 = np.random.normal(loc = 30, scale=2.5, size= N)
random_y2 = np.random.randint(low = 0, high=50, size= N)
random_y3 = np.random.uniform(low = 0, high=20, size= N)

In [18]:
x,random_y1

(array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
        0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
        0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
        0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
        0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
        0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
        0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
        0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
        0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
        0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ]),
 array([28.77180715, 29.52344251, 30.78210524, 26.46727957, 30.71763779,
        29.93905847, 28.47429721, 30.90971303, 22.94886041, 30.79549753,
        29.28838697, 31.22326756, 28.55058306, 30.95578183, 30.67183978,
        29.78230569, 29.83664696, 29.67749733, 31.09079592, 26.80882234,
        27.37582192, 30.05

In [24]:
linha1 = go.Scatter(
    x = x,
    y = random_y1,
    mode = 'lines',
    name = 'Linha 1'
)
linha2 = go.Scatter(
    x = x,
    y = random_y2,
    mode = 'lines+markers',
    name = 'Linha 2',
    line = dict(color='black', width = 1)
)
linha3 = go.Scatter(
    x = x,
    y = random_y3,
    mode = 'lines',
    name = 'Linha 3'
)

data = [linha1,linha2,linha3]

layout = go.Layout(
    title='Minha figura',
    xaxis=dict(title='Eixo X'),
    yaxis=dict(title='Eixo Y')
)

fig = go.Figure(data, layout)
fig.show()


In [39]:
# Outra forma de plotar o gráfico acima
from turtle import title


fig = go.Figure()

fig.add_trace(go.Scatter(x=x, 
                y=random_y1,
                mode = 'lines', 
                line=dict(color='#d3d3d3'),
                name='Linha 1'
    )
)
fig.add_trace(go.Scatter(x=x, 
                y=random_y2,
                mode = 'lines+markers', 
                line=dict(color='#2F4F4F'),
                name='Linha 2',
                marker=dict(size=5, color='red')
    )
)
fig.add_trace(go.Scatter(x=x, 
                y=random_y3,
                mode = 'lines', 
                line=dict(color='#696969',dash='dot',width=2),
                name='Linha 3'
    )
)
fig.update_layout(
    plot_bgcolor='white',
    title='Minha figura',
    font_family='Arial',
    font_color='gray',
    title_font_color='black',
    xaxis=dict(title='Eixo x'),
    yaxis=dict(title='Eixo y'),
    legend_title='Linhas',
    legend_title_font_color = 'black'

)
fig.show()